### PR TITLE
feat: add otel export to logs

### PR DESCRIPTION
**Pull request by arthur-observe**
Add otel logging to collector function.

Split main into 2 functions that can be called by separate cloud functions.

Add sleep to list for API limits

### CODE REVIEW

**Comment by arthur-observe** [comment]
Creating a collector is necessary - adding this to an ubuntu 20.04 startup does the trick
`echo "
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  logging:
    logLevel: debug
  otlphttp:
    endpoint: "https://collect.${var.observe.domain}/v1/otel"
    headers:
      'Authorization': 'Bearer ${var.observe.customer_id} ${var.observe.datastream_token}'
  prometheusremotewrite:
    endpoint: "https://collect.${var.observe.domain}/v1/prometheus"
    headers:
      'Authorization': 'Bearer ${var.observe.customer_id} ${var.observe.datastream_token}'

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check,pprof,zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
  " > /home/ubuntu/otel-collector-config.yaml

sudo apt-get -y install wget systemctl

wget https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v0.69.0/otelcol_0.69.0_linux_amd64.deb

sudo dpkg -i otelcol_0.69.0_linux_amd64.deb

sudo mv /etc/otelcol/config.yaml /etc/otelcol/config.yaml.OLD

sudo cp /home/ubuntu/otel-collector-config.yaml /etc/otelcol/config.yaml

sudo systemctl restart otelcol`

**Comment by arthur-observe** [comment]
Produces output that looks like this it OTEL app
image

image

**Comment by luke-zhu** [comment]
I think this would be nice to have.

I guess there's probably no big use case for this yet, but it seems nice to be able to show customers how to bypass GCP/CloudWatch costs by sending data to an OpenTelemetry Collector instead.

**Comment by yasar-observe** [comment]
Closing the PR as it's no longer relevant but leaving the branch as it could be useful to reference in the future (i.e. code hoarding)

**Pull request closed without merging**
